version: '3.7'

services:

  db:
    image: postgres:12
    container_name: "kippo-postgres-12"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: kippo_local_testing

  localstack:
    image: localstack/localstack:0.11.5
    container_name: "kippo-localstack-0.11.5"
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs

  wait:
    image: waisbrot/wait
    depends_on:
      - localstack
    environment:
      - TARGETS=localstack:4566
