# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: mdillon/postgis:9.6
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
      - image: localstack/localstack:0.11.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-{{ .Branch }}-
      - run:
          name: Upgrade pipenv
          command: |
            python3.7 -m pip install pipenv -U
      - run:
          name: install dependencies
          command: |
            python3.7 -m pipenv sync --dev

      - save_cache:
          key: v2-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv
            - /usr/local/bin
            - /usr/local/bin/lib/python3.7/site-packages

      - run:
          name: prepare database
          command: |
            cd kippo
            python3.7 -m pipenv run python manage.py migrate

      - run:
          name: run tests
          command: |
            make test

      - run:
          name: run code checks
          command: |
            python3.7 -m pipenv run make check

      - store_artifacts:
          path: test-reports
          destination: test-reports